### ISSUE TITLE
Daemon connection breaks because of a trailing "<"

### ISSUE THREAD

**Issue by grcasanova** [monero-ecosystem/monero-javascript#45]
When trying
```
let daemon = monerojs.connectToDaemonRpc("http://localhost:18081", "username", "password");
let height = await daemon.getHeight(); 
```
the console logs an error:

`SyntaxError: Unexpected token '<'`

I am sure it has nothing to do with my code, it only appears when pasting in the monero lib code.

--------------------------------------------------------

Unrelated, but it may be worth investigating
`Needs multisig export info from more participants`
when syncing a 2/3 multisig wallet with just one _msInfo_, requesting to have the export ms data from both users when you actually just need one _msInfo_ to perform the operation.

**Comment by woodser** [comment]
https://github.com/monero-ecosystem/monero-javascript/commit/1bff0aa2e97e33fc9f06f14bda883a915e8c7f8b should resolve the unexpected token issue.

Regarding multisig, the library should be consistent with [monero-wallet-rpc](https://github.com/monero-project/monero/blob/b7425c14c8e7f2fda81d345829ff7e1bc0c382d3/src/wallet/wallet_rpc_server.cpp#L3895) which gives the error `Needs multisig export info from more participants` if the number of imported peer multisig hexes is less than threshold - 1.

I observe importing 1 peer multisig hex at a time to a 2/3 wallet later gives the error "-35: Failed to sign multisig tx: This signature was made with stale data: export fresh multisig data, which other participants must then use." when signing a tx, which may be an issue in monero-wallet-rpc.  These should be tracked separately and with [monero-project](https://github.com/monero-project/monero/issues).

**Comment by grcasanova** [comment]
I tried to step in with a debugger, the daemon object is successfully created (more info as follows) while the error `SyntaxError: Unexpected token '<'` seems to appear when calling `getHeight()`

Print of the daemon var:
```
_proxyPromise: : Promise
      status: "pending"

config: Object
     password: "password"
     pollInterval: 5000
     proxyToWorker: true
     rejectUnauthorized: undefined
     uri: "http://localhost:18081"
     username: "username"
```

Regarding the question about multisig import, considering the case of 2/3 wallets, it is expected that two signers (thus N-1) can exchange info and complete the sync procedure. The stale data error happens with signing and submitting the transaction and isn't involved in the sync procedure (export from A then import from B, then viceversa) while the error `Needs multisig export info from more participants` shouldn't be raised by a 2/3 wallet as long as the import function argument is not null. 

This is my current test setup:
```
let hex = '40324...'; // taken from RPC function export_multisig_info()
walletRpc.importMultisigHex(hex);
```

**Comment by woodser** [comment]
> Ok I solved the problem of the trailing < by enabling cors on the daemon

This allowed the library to successfully connect from a browser.  https://github.com/monero-ecosystem/monero-javascript/commit/1bff0aa2e97e33fc9f06f14bda883a915e8c7f8b makes it so an informative error is given if it can't connect instead of the reported unexpected token.

> and by disabling the webWorker that was somehow blocking the call

The web worker runs local daemon and wallet operations off the main thread so the browser doesn't block.  If you elaborate on this issue I can look into it further.

> the error Needs multisig export info from more participants shouldn't be raised by a 2/3 wallet as long as the import function argument is not null.

This was the result of the library expecting a string[] passed to `importMultisigHex()`.  https://github.com/monero-ecosystem/monero-javascript/commit/b20ae82a7c20a9c6c5c043164d068ff5fee83861 adds support for passing a single string.

> The stale data error happens with signing and submitting the transaction

This behavior should now be consistent with monero-wallet-rpc if there is an issue here.

**Comment by grcasanova** [comment]
Can't you just use an async callback to connect to the daemon, similarly to the wallet RPC? Apparently the webWorker blocks the execution or returns an invalid handle, raising the error.

Regarding the `importMultisigHex()` I still get the same error. I think you need to stick to the curl example [here](https://www.getmonero.org/resources/developer-guides/wallet-rpc.html#import_multisig_info)

- for a single key

`curl http://localhost:18082/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"import_multisig_info","params":{"info":["...multisig_info..."]}}' -H 'Content-Type: application/json'`

- for multiple keys

`curl http://localhost:18082/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"import_multisig_info","params":{"info":["...multisig_info...", "...multisig_info..."]}}' -H 'Content-Type: application/json'`

The info parameter needs to have an array, despite having just a single element.

**Comment by woodser** [comment]
> The info parameter needs to have an array, despite having just a single element.

I reverted `importMultisigHex()` back to expect string[], throwing an error if not given. https://github.com/monero-ecosystem/monero-javascript/commit/5c3878df84070e28d202e52a0adac81ec5f16c77

I don't get the error `Needs multisig export info from more participants` with this change in the RPC or WASM wallets.

Please let me know if you see any behavior different from monero-wallet-rpc.

**Comment by grcasanova** [comment]
I still see a wrong RPC command being sent to monero-wallet-rpc

`Request: 'import_multisig_info' with params: {"info":"4d6f6e65726f206d756c7469736967206578706f727401d2cb3c8b50d5534bca0ad37756cc0067602ec3b668147..."}
`
Whereas it should be
`{"info":["4d6f6e65726f206d756c7469736967206578706f727401d2cb3c8b50d5534bca0ad37756cc0067602ec3b668147..."]}`

Probably for a faster debugging we can chat somewhere in real time and test it?

**Comment by woodser** [comment]
https://github.com/monero-ecosystem/monero-javascript/commit/5c3878df84070e28d202e52a0adac81ec5f16c77 should enforce passing an array.  The input type is documented [here](https://moneroecosystem.org/monero-javascript/MoneroWallet.html#importMultisigHex).

> When calling sweepUnlocked() or createTxs(), how can I get the txKey to sign and submit the transfer?

The transaction key can be retrieved with `tx.getKey()`.

To get unsigned tx hex for signing and submitting transactions created with `createTxs()` or `sweepUnlock()` from view-only and offline wallets:

```
let txs = await viewOnlyWallet.createTxs(...);
let unsignedTxHex = txs[0].getTxSet().getUnsignedTxHex()
let signedTxHex = await offlineWallet.signTxs(unsignedTxHex)
let submittedTxHashes = await offlineWallet.submitTxs(signedTxHex).
```

More documentation on view-only and offline wallets [here](https://github.com/monero-ecosystem/monero-javascript/blob/master/docs/developer_guide/view_only_offline.md).

Or of course you can call `createTxs()` or `sweepUnlock()` with `relay: false` and relay the returned txs later.

**Comment by grcasanova** [comment]
Sorry that's not possible.
`TypeError: tx.getKey is not a function. (In 'tx.getKey()', 'tx.getKey' is undefined)`

`sweepUnlocked()` returns an instance of `MoneroTxWallet` but the method `getKey` is missing

**Comment by woodser** [comment]
`getKey()` is a function on the type `MoneroTxWallet`.  `createTxs()` and `sweepUnlocked()` return  `MoneroTxWallet[]` so the tx key can be retrieved with:

```
let txs = await wallet.createTxs(...);
let txKey = txs[0].getKey()
```

But this is different from tx hex to sign and submit.

If the wallet is a normal, non-view-only, non-offline, non-multisig wallet, you can call `createTxs()` or `sweepUnlocked()` with `relay: false` then call txs[0].getMetadata() to get a string which can be relayed with `relayTx()` to submit the tx.

If the wallet is view-only, you can get the common tx set shared among txs to get the unsigned tx hex to sign and submit:

```
let txs = await viewOnlyWallet.createTxs(...);
let unsignedTxHex = txs[0].getTxSet().getUnsignedTxHex();
let signedTxHex = await offlineWallet.signTxs(unsignedTxHex);
let submittedTxHashes = await offlineWallet.submitTxs(signedTxHex);
```

If the wallet is multisig, you can get the common tx set shared among txs to get the multisig tx hex to sign among participants:

```
let txs = await multisigWallet.createTxs(...);
let multisigTxHex = txs[0].getTxSet().getMultisigTxHex();
```

There are tests I can point you to for usage examples if needed.

**Comment by grcasanova** [comment]
Have you tested the multisig signing process?
I struggle to get a valid txSet.

```
let tx = await walletRpc.sweepUnlocked({ address:'4x35...', relay: true});
console.log( tx[0].getTxSet().getMultisigTxHex() )
```

when sending the key to sign and submit the transaction I get an invalid _multisig_txset_ error, something that has never happened when using monero C++ library.

**Comment by woodser** [comment]
> Have you tested the multisig signing process?

Yes, `sweepUnlocked()` is tested with a multisig wallet [here](https://github.com/monero-ecosystem/monero-javascript/blob/744188214fdcdc68549788e0aaddead545455ec4/src/test/TestMoneroWalletCommon.js#L3940).

**Comment by woodser** [comment]
Closing this since the original issue is resolved.  Please open another issue if further help is needed.
